use_frameworks!

platform :ios, '8.0'

target 'SKNetworking_Example' do
  pod 'SKNetworking', :path => '../'

  target 'SKNetworking_Tests' do
    inherit! :search_paths
    pod 'AFNetworking'
#    pod 'FBSnapshotTestCase'
  end
end
